"""Transporte y parseo aislados del sumario diario del BOE."""

from infocs.fetch.boe.models import (
    BOEDepartment,
    BOEDiary,
    BOEDocumentLinks,
    BOEFetchResult,
    BOEFetchStatus,
    BOEHeading,
    BOEItem,
    BOESection,
    BOESummary,
    BOETerritorialDecision,
    BOETerritorialDecisionStatus,
    BOETerritorialField,
    BOETerritorialMatch,
    BOETerritorialMatchReason,
)
from infocs.fetch.boe.normalize import (
    BOENormalizationError,
    category_for_boe_section,
    normalize_boe_item,
)
from infocs.fetch.boe.ingest import (
    BOE_COLLECTION_SEMANTICS,
    BOECollectionSemantics,
    BOEIngestionError,
    BOEIngestionMetrics,
    BOEIngestionResult,
    BOEIngestionStatus,
    BOEOperation,
    BOEOperationType,
    ingest_boe_summary,
)
from infocs.fetch.boe.parser import BOEContractError, parse_boe_summary
from infocs.fetch.boe.territorial import (
    BOETerritorialEntity,
    BOETerritorialEntityKind,
    BOETerritorialRegistry,
    BOETerritorialRegistryError,
    decide_boe_territorial_inclusion,
    load_castellon_registry,
)
from infocs.fetch.boe.transport import BOETransport

__all__ = [
    "BOEContractError",
    "BOE_COLLECTION_SEMANTICS",
    "BOECollectionSemantics",
    "BOEIngestionError",
    "BOEIngestionMetrics",
    "BOEIngestionResult",
    "BOEIngestionStatus",
    "BOENormalizationError",
    "BOEDepartment",
    "BOEDiary",
    "BOEDocumentLinks",
    "BOEFetchResult",
    "BOEFetchStatus",
    "BOEHeading",
    "BOEItem",
    "BOESection",
    "BOESummary",
    "BOETerritorialDecision",
    "BOETerritorialDecisionStatus",
    "BOETerritorialEntity",
    "BOETerritorialEntityKind",
    "BOETerritorialField",
    "BOETerritorialMatch",
    "BOETerritorialMatchReason",
    "BOETerritorialRegistry",
    "BOETerritorialRegistryError",
    "BOETransport",
    "BOEOperation",
    "BOEOperationType",
    "decide_boe_territorial_inclusion",
    "category_for_boe_section",
    "load_castellon_registry",
    "ingest_boe_summary",
    "normalize_boe_item",
    "parse_boe_summary",
]
